#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
clear
printf "${blu}Welcome To Fedora Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Fedora"
printf "\n\n"
printf "${ylw}• Fedora 39 (Container)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Fedora39\n"
printf "${blu}Version ${red}: ${grn}39.0\n"
printf "${blu}Status  ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs  ${red}: ${grn}Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Fedora 38 (Container)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Fedora38\n"
printf "${blu}Version ${red}: ${grn}38.0\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Fedora 37 (Container)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Fedora37\n"
printf "${blu}Version ${red}: ${grn}37.0\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Fedora 36 (Container)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Fedora36\n"
printf "${blu}Version ${red}: ${grn}36.1.5\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Fedora39")
wget https://raw.githubusercontent.com/wahasa/Fedora/main/Install/fedora39.sh ; chmod +x fedora39.sh ; bash fedora39.sh
        ;;
        "Fedora38")
wget https://raw.githubusercontent.com/wahasa/Fedora/main/Install/fedora38.sh ; chmod +x fedora38.sh ; bash fedora38.sh
        ;;
        "Fedora37")
wget https://raw.githubusercontent.com/wahasa/Fedora/main/Install/fedora37.sh ; chmod +x fedora37.sh ; bash fedora37.sh
        ;;
        "Fedora36")
wget https://raw.githubusercontent.com/wahasa/Fedora/main/Install/fedora36.sh ; chmod +x fedora36.sh ; bash fedora36.sh
	;;
        "Fedora35")
wget https://raw.githubusercontent.com/wahasa/Fedora/main/Install/fedora35.sh ; chmod +x fedora35.sh ; bash fedora35.sh
        ;;
        *)
	bash Install
        ;;
esac
